apiVersion: v1
kind: Secret
metadata:
  name: accessos-secrets
type: Opaque
stringData:
  # Your company domain (ex: accessos.newco.com)
  domain: "{YOUR-COMPANY-DOMAIN}"
  # Postgres Database URL
  postgres-host: "{YOUR-POSTGRES-HOST}"
  postgres-user: "postgres"
  postgres-password: "{YOUR-POSTGRES-PASSWORD}"
  postgres-port: "5432"
  postgres-database: "accessos"
  # Google OAuth Client
  google-client-id: "{YOUR-GOOGLE-OAUTH-CLIENT-ID}"
  google-client-secret: "{YOUR-GOOGLE-OAUTH-CLIENT-SECRET}"
  # Use http secureOnly cookies (requires TLS setup)
  cookie-secure: "true"
