# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: accessos-tls-secrets
type: kubernetes.io/tls
# Note: These values are supposed to be the empty string. We just need some values here
# to bootstrap the Let's Encrypt process.
# See this guide for more details: https://cert-manager.io/docs/tutorials/getting-started-with-cert-manager-on-google-kubernetes-engine-using-lets-encrypt-for-ingress-ssl/#8-re-configure-the-ingress-for-ssl
stringData:
  tls.key: ""
  tls.crt: ""
